version: 1.0.{build}
image: Visual Studio 2017

configuration:
- Release
- Debug

cache:
- build/lib -> appveyor.yml

before_build:
- cmd: >-
    git submodule update --init --recursive
    
    if not exist build\ mkdir build
    cd build
    
    cmake -G "Visual Studio 15 2017 Win64" ../
    
build:
  project: build/PACKAGE.vcxproj
  parallel: true
  verbosity: minimal
  
after_build:
- cmd: >-
    7z a sunken_%CONFIGURATION%_win64.zip %APPVEYOR_BUILD_FOLDER%/build/bin/%CONFIGURATION%/sunken_main.exe %APPVEYOR_BUILD_FOLDER%/build/bin/%CONFIGURATION%/*.dll  %APPVEYOR_BUILD_FOLDER%/build/bin/%CONFIGURATION%/**/*
    
    cd ../build/installer/
    
    dir
    
    for %%a in (*.exe) do ren "%%~a" "%%~na_%CONFIGURATION%_win64%%~xa"
    
    dir
    
artifacts:
  - path: build/*.zip
    name: sunken_zip
  - path: build/installer/*.exe
    name: sunken_installer
    
deploy:
- provider: GitHub
  on:
    appveyor_repo_tag: true
    CONFIGURATION: Release
  auth_token:
    secure: ECVq3ge/gI4xSJEeoXNUiE3fq0samUls/hSKmaGeJmk3CAxEqr02LX2tcVenpINm
  artifact: sunken_installer, sunken_zip
  prerelease: true